# Base configurations for runs
base-configs:
    # Root directory of where the repo is located
    root-directory: '/Users/andreguimaraes/Dropbox/Personal Projects/FlightPathAnalysis/'
    # Tag for current run for log files
    tag: 'test'

# All configurations for gathering data
data-gather:
    # Configurations interesting for gathering flight data.
    flights:
        # hostname of the server
        hostname: 'data.opensky-network.org'
        # port through which to ssh
        port: 2230
        # Routes of interest to be downloaded on the data gathering step
        routes-of-interest: [
        ['KBTR','KDFW'],
        ['KJFK','EGLL'],
        ]
        # Starting date of flights of interest
        start-date: '2020-01-01'
        # Ending date of flights of interest
        end-date: '2021-01-01'

data-compression:
    spline-compressor:
        pearson_corr_range_threshold: 0.99
        s_minimum_precision: 0.01
        s_base_precision: 10000000000000000
        
  
log:
    # Directory where log files are located from the root directory
    log-directory: 'logs/'

