# Base configurations for runs
base-configs:
    # Root directory of where the repo is located
    root-directory: '/Users/andreguimaraes/Dropbox/Personal Projects/FlightPathAnalysis/'
    # Tag for current run for log files
    tag: 'data_gather_test'
    # File containing the credentials for OpenSky database
    opensky-credentials: 'config/opensky_login.yml'
    # FIle containing the credentials for the weather database
    weather-credentials:

# All configurations for gathering data
data-gather:
    # Configurations interesting for gathering flight data.
    flights:
        # directory to output data at from the root directory
        out-dir: 'data/flight/'
        # hostname of the server
        hostname: 'data.opensky-network.org'
        # port through which to ssh
        port: 2230
        # Routes of interest to be downloaded on the data gathering step
        routes-of-interest: [
        ['KJFK','KLAX']
        ]
        # Starting date of flights of interest
        start-date: '2023-01-01'
        # Ending date of flights of interest
        end-date: '2023-02-01'
        # Bad Days csv
        bad-days-csv: 'data/flight/bad_days.csv'
        # Size of per chunk of data to gather (in seconds)
        chunk-size: 604800
        # Time limit in seconds until a retry is required for gathering flights data
        flight-data-timeout: 300
        # Number of retries for gathering flight data
        flight-data-retries: 3
        # Time limit in seconds until a retry is required for gathering state vectors
        state-vector-timeout: 300
        # Number of retries for gathering state vectors
        state-vector-retries: 3
        # Continue data gather from last attemp. If False, it will start from scratch
        continue-from-last: True

# All configurations for data compression
data-compression:
    # Which compressor to use in the data
    compressor: 'csv-compressor'
    # Configurations defining the CSV-compression algorithm
    csv-compressor:
        # Number of interpolated points to be saved in the csv compression
        num-points: 1000
    # Configurations defining the spline-compression algorithm
    spline-compressor:
        # The Maximum alowed percentage error between the data and the interpolation
        max-error: 0.01
        # Smallest precision step to which narrow down s
        s-minimum-precision: 0.001
        # Initial precisionf step of s, must be large
        s-base-precision: 10000000000000000
        # Degree of the spline to be used
        degree: 2

# Configurations for the statistical analysis of the data 
statistics:
    # Routes to be analyzed
    routes-to-analyze: [
    ['KJFK','KLAX']
    ]

# configurations for the plotting of the data and analysis
plotting:
    # x and y dimensions of the plot figures
    fig-size: [10, 6.17]
    # Font size of the axis
    axis-fontsize: 20
    # Font size of the tick labels
    tick-fontsize: 15
    # Font size of the title
    title-fontsize: 25
    # Font size of the legend
    legend-fontsize: 15
    # Default color map to be used
    cmap: 'cool'
    # Number of points to be used in lines
    point-precision: 1000
    # Expectation value to be used when plotting
    expectation-measure: 'mean'
    # Deviation measure to be used when plotting
    deviation-measure: 'std'
    # Deviation values to be used when plotting.
        # If std, numbers indicate how many standard deviations to plot ([1,2,3] -> plots 1, 2, and 3 sigmas)
        # if pct, indicated which percentiles to plot ([50, 75, 90] -> plots 50th, 75th, and 90th percentiles)
    deviation-values: [1, 2, 3]
    # Extent of min and max values longitude and latitude (respectively) to be plotted: [min_lon, max_lon, min_lat, max_lat]
    # If left blank or None, it will be automatically calculated for the corresponding data.
        # United States: [-121, -71, 13, 66]
    map-extent: [-121, -71, 13, 66]

# All configurations for logging messages
log:
    # Directory where log files are located from the root directory
    log-directory: 'logs/'

