# Base configurations for runs
base-configs:
    # Root directory of where the repo is located
    root-directory: '/Users/andreguimaraes/Dropbox/Personal Projects/FlightPathAnalysis/'
    # Tag for current run for log files
    tag: 'test'
    # File containing the credentials for OpenSky database
    opensky-credentials: 'config/opensky_login.yml'
    # FIle containing the credentials for the weather database
    weather-credentials:

# All configurations for gathering data
data-gather:
    # Configurations interesting for gathering flight data.
    flights:
        # directory to output data at from the root directory
        out-dir: 'data/flight/'
        # hostname of the server
        hostname: 'data.opensky-network.org'
        # port through which to ssh
        port: 2230
        # Routes of interest to be downloaded on the data gathering step
        routes-of-interest: [
        ['KBTR','KDFW'],
        ['KJFK','EGLL'],
        ]
        # Starting date of flights of interest
        start-date: '2020-01-01'
        # Ending date of flights of interest
        end-date: '2021-01-01'

# All configurations for data compression
data-compression:
    # Configurations defining the spline-compression algorithm
    spline-compressor:
        # The Maximum alowed percentage error between the data and the interpolation
        max-error: 0.05
        # Smallest precision step to which narrow down s
        s-minimum-precision: 0.01
        # Initial precisionf step of s, must be large
        s-base-precision: 10000000000000000
        
# All configurations for logging messages
log:
    # Directory where log files are located from the root directory
    log-directory: 'logs/'

