Reflectivity_HI:
    "units": "dBZ"
    "scale_factor": 0.5
    "offset": -33.0
    "timeR_HI":
        "units": "msecs since 2008-03-30T13:18:26Z"
    "elevationR_HI":
        "units": "degrees"
    "azimuthR_HI":
        "units": "degrees"
    "distanceR_HI":
        "units": "m"
Reflectivity:
    "units": "dBZ"
    "scale_factor": 0.5
    "offset": -33.0
    "timeR":
        "units": "msecs since 2008-03-30T13:18:26Z"
    "elevationR":
        "units": "degrees"
    "azimuthR":
        "units": "degrees"
    "distanceR":
        "units": "m"
RadialVelocity_HI:
    "units": "m/s"
    "scale_factor": 0.5
    "offset": -64.5
    "timeV_HI":
        "units": "msecs since 2008-03-30T13:18:26Z"
    "elevationV_HI":
        "units": "degrees"
    "azimuthV_HI":
        "units": "degrees"
    "distanceV_HI":
        "units": "m"
RadialVelocity:
    "units": "m/s"
    "scale_factor": 0.5
    "offset": -64.5
    "timeV":
        "units": "msecs since 2008-03-30T13:18:26Z"
    "elevationV":
        "units": "degrees"
    "azimuthV":
        "units": "degrees"
    "distanceV":
        "units": "m"
